[project]
site_name = "Confidantic"
site_description = "Configuration and CLIs for Python projects based on Pydantic and Pydantic Settings."
site_author = "Szymon Talaga"
site_url = "https://sztal.github.io/confidantic/"
copyright = "Copyright &copy; 2026 Szymon Talaga"
repo_url =  "https://github.com/sztal/confidantic"
repo_name = "sztal/confidantic"
edit_uri = "edit/main/docs/"
nav = [
  { "Home" = [
    "index.md",
    { "Release notes" = "changelog.md" },
    { "License" = "license.md" },
  ] },
  { "Reference" = [
    "reference/index.md",
    { "API" = "reference/api.md" },
  ] },
]

[project.theme]
features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "content.tooltips",
  "navigation.footer",
  "navigation.indexes",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sztal/confidantic"

[project.markdown_extensions]
pymdownx.highlight = { anchor_linenums = true, pygments_lang_class = true }
pymdownx.snippets = {}
pymdownx.superfences = {}
pymdownx.tabbed = { alternate_style = true }

[project.plugins.mkdocstrings.handlers.python]
inventories = [
  "https://docs.python.org/3/objects.inv",
]

[project.plugins.mkdocstrings.handlers.python.options]
parameter_headings = true
show_root_heading = true
show_symbol_type_heading = true
show_symbol_type_toc = true
type_parameter_headings = true
inherited_members = true
members_order = "source"
summary = true
docstring_style = "google"
docstring_options = { ignore_init_summary = true }
docstring_section_style = "table"
merge_init_into_class = true
show_signature_annotations = true
show_signature_type_parameters = true
separate_signature = true
signature_crossrefs = true
